In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_diabetes

In [5]:
dia = load_diabetes()
dia

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [7]:
print(dia.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

In [8]:
dia.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [9]:
dia.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

In [10]:
dia.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [12]:
data = pd.DataFrame(dia.data , columns = dia.feature_names)
data

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [14]:
data["target"] = dia.target
data

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [15]:
# EdA and data preparation

In [16]:
x = data.drop("target", axis = 1)
y = data['target']

In [17]:
x

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [18]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [19]:
# split the data into train and test

from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test = train_test_split(x , y , test_size = 0.2 , random_state = 1)

In [21]:
x_train.shape , x_test.shape

((353, 10), (89, 10))

In [22]:
# scaling

from sklearn.preprocessing import StandardScaler

In [23]:
scaler = StandardScaler()
scaler

StandardScaler()

In [24]:
# scaling should be done always after train test split
# target varible should not  be scaled 
# avoid scaling categorincal features 


x_train = scaler.fit_transform(x_train) # for train data use fit_transform
x_test = scaler.transform(x_test)             # for test data use transform

In [25]:
x_train

array([[-0.11368353,  1.07965002, -0.36752752, ...,  0.69608315,
        -0.38903096,  0.87895653],
       [ 0.26997121,  1.07965002, -0.03095571, ...,  1.15378737,
         0.48240441,  0.6242179 ],
       [ 1.49766635, -0.92622607,  0.21586362, ..., -0.07968673,
         0.51009593, -0.139998  ],
       ...,
       [-1.80176435,  1.07965002, -0.68166122, ..., -0.85545661,
        -2.00757238, -0.73438814],
       [ 1.4209354 ,  1.07965002, -0.3450894 , ...,  0.24613662,
        -0.12096945,  0.96386941],
       [-0.19041447, -0.92622607,  0.1934255 , ..., -0.85545661,
         0.33735356, -0.139998  ]], shape=(353, 10))

In [27]:
x_test

array([[ 8.83818777e-01, -9.26226072e-01, -7.04099342e-01,
        -1.31658142e+00,  1.65824051e+00,  1.06541001e+00,
         1.21435237e+00, -2.34840706e-01,  9.16615064e-01,
        -1.24386541e+00],
       [-1.64830246e+00, -9.26226072e-01, -8.83604310e-01,
        -1.72620332e+00, -2.13489443e+00, -2.41397635e+00,
         5.06787494e-01, -1.63122648e+00, -4.34053233e-01,
        -1.07403966e+00],
       [-1.49484056e+00, -9.26226072e-01,  1.89872271e+00,
         2.48217552e-01,  4.13165684e-01,  8.85785853e-01,
         3.50775787e-02, -1.76251400e-02, -1.14178835e+00,
        -5.50851245e-02],
       [-4.97338259e-01, -9.26226072e-01, -1.39968110e+00,
        -1.72620332e+00, -8.31909146e-01, -1.15660729e+00,
         1.29297068e+00, -1.63122648e+00, -7.81986893e-01,
        -9.04213900e-01],
       [ 8.07087831e-01,  1.07965002e+00,  8.12348974e-02,
         6.57839445e-01,  1.23613398e-01,  3.53566143e-01,
        -5.15250655e-01,  6.96083147e-01,  2.91577769e-01,
         1.21860804e+00],
       [ 8.83818777e-01,  1.07965002e+00,  3.72930472e-01,
         1.23578921e+00, -1.36983659e-01, -7.22096254e-02,
        -5.93868974e-01, -7.96867301e-02,  6.29904165e-01,
         1.14740631e-01],
       [ 1.26747351e+00,  1.07965002e+00,  1.56215089e+00,
         5.13352005e-01,  7.79248362e-03,  3.40260650e-01,
        -1.14419721e+00,  6.96083147e-01,  6.03908039e-01,
         8.78956528e-01],
       [ 8.83818777e-01,  1.07965002e+00, -3.67527525e-01,
         3.45024137e-01, -8.02953917e-01, -3.11708495e-01,
        -5.15250655e-01, -2.58113802e-01, -9.83551060e-01,
         2.84566386e-01],
       [ 8.83818777e-01,  1.07965002e+00, -5.02156252e-01,
         5.85595725e-01, -1.41101372e+00, -9.76983133e-01,
        -1.30143385e+00, -7.96867301e-02,  4.44261918e-02,
        -1.15895253e+00],
       [ 1.16509313e-01, -9.26226072e-01, -7.93851826e-01,
         4.41108285e-01,  6.57029408e-02,  3.13649665e-01,
         1.92314217e-01, -7.96867301e-02, -6.75741856e-01,
        -9.89126778e-01],
       [-9.57723938e-01, -9.26226072e-01,  7.76816652e-01,
         7.64596425e-03,  3.26299998e-01,  3.06996918e-01,
        -5.93868974e-01,  5.33171473e-01,  9.05500778e-01,
        -5.64562390e-01],
       [ 2.69971205e-01, -9.26226072e-01, -4.57280009e-01,
        -3.53572636e-01,  2.39434312e-01,  4.33399100e-01,
        -1.61590712e+00,  2.24762290e+00,  1.22272887e+00,
        -4.79649512e-01],
       [ 1.19074256e+00,  1.07965002e+00, -6.81661220e-01,
         1.52133404e-01,  3.84210455e-01,  4.33399100e-01,
         7.42642451e-01, -8.55456607e-01, -6.24879870e-01,
        -1.24386541e+00],
       [-1.13683527e-01,  1.07965002e+00, -8.51758705e-03,
        -1.79844704e+00, -2.52804574e-01, -3.71583213e-01,
         1.05711573e+00, -8.55456607e-01, -8.65626604e-01,
        -1.83825555e+00],
       [-1.13683527e-01, -9.26226072e-01,  8.66569136e-01,
         1.81373897e+00,  2.68389541e-01,  1.34025512e-01,
        -2.79395698e-01, -7.96867301e-02,  8.60290124e-01,
        -3.94736635e-01],
       [-1.13683527e-01, -9.26226072e-01,  1.31533156e+00,
         7.30083165e-01, -5.01179736e-02,  3.00344172e-01,
        -2.79395698e-01, -9.86744121e-03, -3.89030956e-01,
         6.24217896e-01],
       [ 9.60549724e-01,  1.07965002e+00, -9.82700715e-02,
         2.24720129e+00,  7.31673198e-01,  4.60010085e-01,
         5.85405813e-01, -7.96867301e-02,  5.64348716e-01,
         3.69479263e-01],
       [-8.80992992e-01, -9.26226072e-01, -7.26537463e-01,
        -4.98060076e-01,  9.63315027e-01,  8.65827614e-01,
         1.21435237e+00, -5.45148656e-01, -5.51035801e-01,
        -8.19301022e-01],
       [ 1.65112824e+00,  1.07965002e+00, -5.47032494e-01,
        -9.07681969e-01,  1.23613398e-01,  1.10532648e+00,
        -1.45867049e+00,  1.67355319e+00, -7.81986893e-01,
         1.13369516e+00],
       [ 3.97783660e-02,  1.07965002e+00,  1.93425503e-01,
        -4.25816356e-01, -3.68625488e-01, -9.88206109e-02,
        -9.86960570e-01,  6.96083147e-01,  4.82404405e-01,
         4.54392141e-01],
       [ 1.03728067e+00,  1.07965002e+00,  3.63586552e-02,
         1.45252037e+00, -1.94894117e-01,  2.67080440e-01,
        -1.14419721e+00,  6.96083147e-01,  2.60495444e-01,
         7.09130773e-01],
       [-3.43876366e-01, -9.26226072e-01, -1.13042364e+00,
        -7.14791236e-01, -9.47730060e-01, -7.90706235e-01,
         4.28169174e-01, -8.55456607e-01, -1.42680385e+00,
        -6.49475267e-01],
       [-1.57157151e+00, -9.26226072e-01, -2.55336919e-01,
        -1.36841476e-01, -1.41101372e+00, -1.22978750e+00,
        -4.35407405e-02, -8.55456607e-01, -8.94448396e-01,
        -5.50851245e-02],
       [-1.95522624e+00, -9.26226072e-01, -8.83604310e-01,
        -4.25816356e-01, -1.46892417e+00, -1.70213249e+00,
         8.99879089e-01, -1.63122648e+00, -8.65626604e-01,
        -2.00808131e+00],
       [-1.11118583e+00, -9.26226072e-01, -1.33236673e+00,
        -5.70303796e-01, -1.36983659e-01, -1.25431596e-01,
         6.64024132e-01, -8.55456607e-01, -6.50122485e-01,
        -1.49860404e+00],
       [ 1.93240259e-01, -9.26226072e-01,  9.11445379e-01,
         5.85595725e-01,  2.39434312e-01, -3.11708495e-01,
         5.85405813e-01, -8.55456607e-01,  9.38655258e-01,
         7.09130773e-01],
       [ 1.93240259e-01, -9.26226072e-01, -5.02156252e-01,
        -6.90950809e-01, -1.06355097e+00, -1.47593911e+00,
         1.68606228e+00, -1.51486100e+00, -1.31490748e+00,
        -8.19301022e-01],
       [-4.97338259e-01, -9.26226072e-01,  7.99254773e-01,
        -2.81328916e-01, -2.23849345e-01, -3.89458935e-02,
        -4.35407405e-02, -7.96867301e-02, -2.60557347e-01,
        -8.19301022e-01],
       [ 8.83818777e-01,  1.07965002e+00, -8.38728068e-01,
         1.09130177e+00,  1.60033006e+00,  2.45583400e+00,
        -8.29723932e-01,  1.47185302e+00, -4.80017398e-01,
        -3.09823757e-01],
       [ 1.49766635e+00,  1.07965002e+00,  2.15863624e-01,
         1.16354549e+00,  7.02717970e-01,  1.03214627e+00,
        -8.29723932e-01,  6.96083147e-01,  5.50785520e-01,
        -5.50851245e-02],
       [ 3.97783660e-02,  1.07965002e+00, -1.65584435e-01,
        -4.25816356e-01, -2.23849345e-01,  8.74562878e-02,
        -8.29723932e-01,  6.96083147e-01,  2.91577769e-01,
         1.98282394e+00],
       [ 1.26747351e+00, -9.26226072e-01, -5.33938293e-02,
        -1.79844704e+00,  1.57137483e+00,  1.67080993e+00,
         1.13695898e-01,  6.96083147e-01,  4.68276076e-01,
         5.39305018e-01],
       [-1.57157151e+00,  1.07965002e+00,  1.11338847e+00,
        -8.59278677e-01,  1.10809117e+00,  1.11197923e+00,
        -9.08342251e-01,  1.47185302e+00,  1.25079715e+00,
        -7.34388145e-01],
       [ 6.53625938e-01, -9.26226072e-01, -7.26537463e-01,
        -4.98060076e-01, -1.00564052e+00, -1.74204897e+00,
         2.23639051e+00, -1.63122648e+00, -8.37369945e-01,
        -1.15895253e+00],
       [ 1.16509313e-01, -9.26226072e-01, -1.24261425e+00,
        -4.98060076e-01, -1.43996895e+00, -1.46928637e+00,
        -1.14419721e+00, -7.96867301e-02,  8.71781165e-01,
        -1.75334268e+00],
       [ 8.07087831e-01,  1.07965002e+00,  3.05616109e-01,
         4.41108285e-01,  8.18538884e-01,  9.39007825e-01,
        -9.08342251e-01,  1.47185302e+00,  1.01381797e+00,
         2.84566386e-01],
       [-1.64830246e+00, -9.26226072e-01, -1.55674794e+00,
        -1.22049728e+00, -1.78743169e+00, -1.59568855e+00,
        -5.15250655e-01, -8.55456607e-01, -3.89030956e-01,
        -1.75334268e+00],
       [-2.67145420e-01, -9.26226072e-01,  1.22557907e+00,
         1.09130177e+00,  9.92270256e-01,  6.06370505e-01,
        -3.58014017e-01,  6.96083147e-01,  1.43616083e+00,
         1.14740631e-01],
       [ 2.03478297e+00, -9.26226072e-01,  7.99254773e-01,
        -1.22049728e+00,  9.34359799e-01,  1.27164514e+00,
        -4.36632336e-01,  7.34871641e-01,  2.44671715e-01,
         4.54392141e-01],
       [-9.57723938e-01,  1.07965002e+00, -5.47032494e-01,
         1.23578921e+00,  9.46581694e-02,  3.00344172e-01,
        -1.14419721e+00,  1.47185302e+00,  8.60290124e-01,
         2.84566386e-01],
       [ 3.46702152e-01,  1.07965002e+00,  1.70987382e-01,
        -9.31522397e-01, -2.04802875e+00, -2.02811706e+00,
        -8.29723932e-01, -8.55456607e-01,  3.37353556e-01,
         1.14740631e-01],
       [ 1.42093540e+00,  1.07965002e+00, -1.65584435e-01,
         1.30803293e+00, -9.18774831e-01, -2.05472805e+00,
         1.13573405e+00, -1.63122648e+00,  1.21330998e+00,
         1.04878228e+00],
       [ 1.49766635e+00,  1.07965002e+00, -6.81661220e-01,
         4.41108285e-01, -8.02953917e-01, -1.01689961e+00,
         7.42642451e-01, -8.55456607e-01, -3.23852263e-01,
        -5.50851245e-02],
       [ 8.07087831e-01,  1.07965002e+00, -3.22651283e-01,
        -3.53572636e-01, -7.73998688e-01, -4.84679901e-01,
        -2.79395698e-01, -7.96867301e-02, -5.51035801e-01,
        -5.50851245e-02],
       [ 9.60549724e-01, -9.26226072e-01, -4.34841888e-01,
         4.41108285e-01,  5.57941827e-01, -3.05055749e-01,
         2.15777220e+00, -8.55456607e-01,  3.52423774e-01,
        -3.09823757e-01],
       [ 1.34420446e+00, -9.26226072e-01, -1.08554740e+00,
         2.24720129e+00,  6.44807513e-01,  3.93482621e-01,
        -3.58014017e-01,  4.71109883e-01,  1.18467657e+00,
         7.94043651e-01],
       [-1.95522624e+00, -9.26226072e-01,  5.52435441e-01,
        -3.53572636e-01,  7.60628427e-01,  5.13232056e-01,
         1.21435237e+00, -8.55456607e-01, -1.20969452e-01,
        -5.50851245e-02],
       [-9.57723938e-01, -9.26226072e-01, -8.38728068e-01,
        -5.70303796e-01, -3.39670259e-01,  9.70584812e-04,
        -6.72487294e-01, -7.96867301e-02,  9.01117928e-03,
        -8.19301022e-01],
       [-6.50800152e-01,  1.07965002e+00,  1.20314095e+00,
         7.64596425e-03,  2.39434312e-01,  6.52939730e-01,
        -9.08342251e-01,  6.96083147e-01,  2.91577769e-01,
         1.14740631e-01],
       [ 1.57439730e+00,  1.07965002e+00, -4.57280009e-01,
         9.46814325e-01,  1.54241960e+00,  6.79550716e-01,
        -7.51105613e-01,  1.47185302e+00,  2.18307852e+00,
         7.09130773e-01],
       [-5.74069206e-01,  1.07965002e+00, -1.88022556e-01,
        -8.59278677e-01, -2.52804574e-01, -3.11708495e-01,
         1.29297068e+00, -8.55456607e-01, -1.71709393e+00,
        -5.64562390e-01],
       [ 5.76894991e-01, -9.26226072e-01,  1.00119786e+00,
        -1.17209398e+00, -7.90732022e-02,  8.45869375e-01,
        -1.22281553e+00,  1.08396809e+00, -1.10919900e+00,
        -1.39998002e-01],
       [ 3.46702152e-01,  1.07965002e+00, -9.73356795e-01,
         1.30803293e+00,  2.10479084e-01, -2.56404007e-02,
         1.37158900e+00, -8.55456607e-01, -6.50122485e-01,
         7.09130773e-01],
       [ 3.46702152e-01, -9.26226072e-01, -1.01823304e+00,
        -6.45977558e-02, -4.26535945e-01, -9.30413909e-01,
         7.42642451e-01, -8.55456607e-01,  5.50785520e-01,
         5.39305018e-01],
       [ 1.26747351e+00,  1.07965002e+00,  4.40244835e-01,
         1.01905805e+00,  3.26299998e-01,  2.33816708e-01,
        -2.79395698e-01, -7.96867301e-02,  8.02458162e-01,
         3.69479263e-01],
       [ 8.83818777e-01,  1.07965002e+00, -3.45089404e-01,
        -3.77413064e-01, -1.36983659e-01,  1.60636498e-01,
        -2.79395698e-01, -6.41713326e-02, -2.60557347e-01,
         2.98277530e-02],
       [ 1.88132108e+00, -9.26226072e-01,  1.03673019e-01,
         5.13352005e-01,  6.15852284e-01,  1.67289244e-01,
         1.37158900e+00, -8.55456607e-01,  1.80246532e-01,
         6.24217896e-01],
       [ 5.00164045e-01,  1.07965002e+00, -6.81661220e-01,
        -1.36841476e-01, -3.68625488e-01,  3.60218889e-01,
        -6.72487294e-01, -7.96867301e-02, -1.54585857e+00,
        -7.34388145e-01],
       [-4.97338259e-01, -9.26226072e-01, -1.48943358e+00,
        -1.36498472e+00, -1.26623757e+00, -1.09007982e+00,
         4.28169174e-01, -8.55456607e-01, -1.85668182e+00,
        -1.07403966e+00],
       [ 2.69971205e-01, -9.26226072e-01, -5.69470615e-01,
        -8.59278677e-01, -6.58177774e-01, -9.76983133e-01,
         1.68606228e+00, -1.63122648e+00, -1.50535736e+00,
         1.99653508e-01],
       [ 8.07087831e-01,  1.07965002e+00, -6.59223099e-01,
        -1.58171588e+00, -2.81759802e-01, -2.85097510e-01,
         1.13695898e-01, -7.96867301e-02,  6.19453204e-02,
        -6.49475267e-01],
       [-1.64830246e+00,  1.07965002e+00,  1.58458901e+00,
         1.09130177e+00,  1.62928528e+00,  1.35147810e+00,
         5.85405813e-01, -7.96867301e-02,  8.25817000e-01,
        -2.24910880e-01],
       [ 4.23433098e-01,  1.07965002e+00,  1.70987382e-01,
         3.68864565e-01,  2.97344770e-01,  9.32355078e-01,
        -1.30143385e+00,  1.47185302e+00,  1.80246532e-01,
        -1.32877829e+00],
       [ 1.93240259e-01, -9.26226072e-01, -4.57280009e-01,
        -1.14825356e+00,  6.44807513e-01,  4.20093607e-01,
         1.21435237e+00, -8.55456607e-01, -2.40024175e-01,
        -5.50851245e-02],
       [-1.11118583e+00,  1.07965002e+00,  2.01091331e+00,
         1.81373897e+00,  1.25286731e+00,  1.01884078e+00,
        -1.22281553e+00,  2.24762290e+00,  1.73134873e+00,
         7.94043651e-01],
       [-8.80992992e-01, -9.26226072e-01, -1.42211922e+00,
        -1.00376612e+00, -8.02953917e-01, -9.37066655e-01,
         1.05711573e+00, -8.55456607e-01, -1.17513121e+00,
        -3.09823757e-01],
       [-9.57723938e-01,  1.07965002e+00, -1.01823304e+00,
        -3.53572636e-01, -8.60864374e-01, -5.44554618e-01,
         3.50775787e-02, -8.55456607e-01, -1.31490748e+00,
        -8.19301022e-01],
       [-8.04262045e-01,  1.07965002e+00,  1.44996029e+00,
        -1.22049728e+00,  3.22182286e+00,  3.29408004e+00,
         3.50775787e-02,  1.48736842e+00,  1.02436712e+00,
         1.38843379e+00],
       [-1.72503340e+00,  1.07965002e+00,  8.44131015e-01,
        -4.25816356e-01,  8.18538884e-01,  1.20511768e+00,
        -1.45867049e+00,  2.24762290e+00,  9.60507075e-01,
        -8.19301022e-01],
       [-5.74069206e-01, -9.26226072e-01, -1.28749049e+00,
        -6.42547516e-01,  9.63315027e-01,  4.06788114e-01,
         2.62948211e+00, -8.55456607e-01, -1.07698641e+00,
        -2.24910880e-01],
       [-1.11118583e+00, -9.26226072e-01, -1.19773801e+00,
        -7.87034956e-01,  1.86092711e+00, -8.55151181e-02,
         1.92314217e-01,  6.96083147e-01,  2.72089693e+00,
         2.98277530e-02],
       [-2.18541908e+00,  1.07965002e+00, -5.24594373e-01,
        -4.98060076e-01, -1.84534215e+00, -1.45598087e+00,
        -3.58014017e-01, -8.55456607e-01, -1.62949828e+00,
        -1.49860404e+00],
       [-4.20607313e-01, -9.26226072e-01, -9.95794916e-01,
        -2.08742192e+00, -1.61370032e+00, -1.28966221e+00,
        -3.58014017e-01, -8.55456607e-01, -1.07698641e+00,
        -9.89126778e-01],
       [ 5.00164045e-01,  1.07965002e+00, -4.34841888e-01,
         1.01905805e+00, -1.35310326e+00, -1.31627320e+00,
         1.13695898e-01, -8.55456607e-01, -5.51035801e-01,
        -3.09823757e-01],
       [ 3.97783660e-02,  1.07965002e+00,  5.07559199e-01,
        -2.09085196e-01,  5.00031370e-01,  7.99300151e-01,
        -4.36632336e-01,  6.96083147e-01,  1.80246532e-01,
         2.98277530e-02],
       [ 8.83818777e-01, -9.26226072e-01, -1.37724297e+00,
         7.30083165e-01,  2.39434312e-01, -1.24974573e+00,
         3.88737522e+00, -1.63122648e+00, -2.73457219e-02,
        -1.07403966e+00],
       [ 1.72785919e+00,  1.07965002e+00, -5.69470615e-01,
        -7.87034956e-01, -1.49787940e+00, -1.00359412e+00,
        -8.29723932e-01, -7.96867301e-02, -8.65626604e-01,
        -1.39998002e-01],
       [-1.80176435e+00,  1.07965002e+00, -8.83604310e-01,
        -7.14791236e-01, -1.72952123e+00, -1.49589735e+00,
        -1.22159060e-01, -8.55456607e-01, -1.20922758e+00,
        -9.04213900e-01],
       [ 6.53625938e-01, -9.26226072e-01,  7.99254773e-01,
         1.59700781e+00,  3.55255227e-01,  7.85994658e-01,
        -5.93868974e-01,  6.96083147e-01, -4.56183613e-02,
         2.40738832e+00],
       [ 3.46702152e-01, -9.26226072e-01,  5.07559199e-01,
         1.21194878e+00, -1.29519280e+00, -9.57024894e-01,
        -2.79395698e-01, -7.39091126e-01, -1.07698641e+00,
        -5.64562390e-01],
       [-5.74069206e-01,  1.07965002e+00, -1.19773801e+00,
         5.13352005e-01, -1.65938888e-01, -5.17943633e-01,
         1.13573405e+00, -8.55456607e-01, -1.20969452e-01,
        -1.07403966e+00],
       [ 1.16509313e-01,  1.07965002e+00, -6.36784978e-01,
        -2.09085196e-01, -6.87133003e-01, -6.31040321e-01,
         1.92314217e-01, -8.55456607e-01, -3.89030956e-01,
         1.14740631e-01],
       [-8.04262045e-01, -9.26226072e-01, -2.55336919e-01,
        -7.87034956e-01, -8.02953917e-01, -4.31457930e-01,
        -5.93868974e-01, -7.96867301e-02, -3.89030956e-01,
        -3.94736635e-01],
       [ 1.16509313e-01,  1.07965002e+00, -2.10460677e-01,
         4.41108285e-01,  1.13704640e+00,  1.53775500e+00,
        -5.15250655e-01,  6.96083147e-01,  2.44671715e-01,
         1.89791106e+00],
       [-7.27531099e-01, -9.26226072e-01, -1.26505237e+00,
         7.64596425e-03, -1.15041666e+00, -1.67552150e+00,
         1.45020732e+00, -1.63122648e+00, -4.56846938e-01,
         2.84566386e-01],
       [ 3.46702152e-01,  1.07965002e+00, -4.79718130e-01,
        -2.09085196e-01,  7.02717970e-01,  9.98882542e-01,
         3.50775787e-02, -7.96867301e-02, -2.81467275e-01,
         4.54392141e-01],
       [ 3.97783660e-02, -9.26226072e-01, -1.51187170e+00,
        -4.98060076e-01, -5.01179736e-02, -3.89458935e-02,
         5.85405813e-01, -8.55456607e-01, -4.80017398e-01,
         1.14740631e-01],
       [-8.04262045e-01, -9.26226072e-01, -1.17529988e+00,
        -1.65395960e+00, -7.16088231e-01, -1.85514566e+00,
         3.02257371e+00, -1.63122648e+00, -4.11447906e-01,
        -1.39998002e-01],
       [-1.03445488e+00, -9.26226072e-01,  3.31232434e+00,
        -1.00376612e+00, -6.29222545e-01, -4.38110676e-01,
        -9.86960570e-01,  6.96083147e-01,  5.64348716e-01,
         1.99653508e-01]])

In [ ]:
# model training 

from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [29]:
model.fit(x_train , y_train)

LinearRegression()

In [30]:
x_train.shape

(353, 10)

In [31]:
model.coef_

array([ -1.44969259, -12.93769125,  25.40335868,  15.61675557,
       -27.61006591,  15.67311145,  -1.30996162,   6.62516243,
        32.1830761 ,   3.01977565])

In [32]:
len(model.coef_)

10

In [33]:
model.intercept_

np.float64(153.37677053824362)

In [35]:
#interpretation
#say age has coef value -30.62219046
#interpretation> 1 unit change in age then target value decreases by -30 units on an average when all
#other features/factors are kept constant
x_train

array([[-0.11368353,  1.07965002, -0.36752752, ...,  0.69608315,
        -0.38903096,  0.87895653],
       [ 0.26997121,  1.07965002, -0.03095571, ...,  1.15378737,
         0.48240441,  0.6242179 ],
       [ 1.49766635, -0.92622607,  0.21586362, ..., -0.07968673,
         0.51009593, -0.139998  ],
       ...,
       [-1.80176435,  1.07965002, -0.68166122, ..., -0.85545661,
        -2.00757238, -0.73438814],
       [ 1.4209354 ,  1.07965002, -0.3450894 , ...,  0.24613662,
        -0.12096945,  0.96386941],
       [-0.19041447, -0.92622607,  0.1934255 , ..., -0.85545661,
         0.33735356, -0.139998  ]], shape=(353, 10))

In [38]:
y_pred = model.predict(x_test)
y_pred

array([119.14235853, 110.77183282, 185.03750644,  68.00997114,
       171.05444208, 190.41916188, 218.59009744, 119.63375975,
       157.26867822, 129.50082172, 214.15123432, 202.9228174 ,
        88.41924038,  71.96523457, 236.88645879, 206.09667095,
       175.60536299, 101.96502781, 114.10950995, 169.04562492,
       187.71464103,  85.64466706, 144.1354953 , 107.06903899,
        94.04844034, 211.79832988,  90.72839769, 176.23084464,
       122.62288816, 180.92495472, 157.11598543, 138.04315918,
       192.36322448,  94.45469648, 166.30860041, 189.43644667,
       110.67690284, 247.6779722 , 172.47370249, 188.08959083,
       160.08451415, 176.65318031, 115.81198266, 120.23187992,
       141.5360933 , 203.4072105 , 152.43166715, 144.09802539,
       190.18999626, 191.4950697 ,  59.81227803, 159.75688911,
       102.14767931, 147.89042458, 186.10407036, 121.41211882,
       159.12303468,  83.43835172,  55.57818196,  79.08303804,
        99.4572998 , 199.89514677, 168.54643127, 109.16305633,
       276.41546587,  76.51059696,  74.13709552, 167.99007114,
       198.23092034,  58.7775995 , 163.54941204,  87.43623443,
        89.56957705, 135.79451579, 158.77561923,  94.27258269,
       108.05111452,  85.56348683, 223.35788159, 176.54241443,
       100.00310086, 110.78621667, 149.69368376, 152.38161737,
       113.34969507, 111.44759595,  98.35464312,  73.10420379,
       270.50448153])

In [39]:
from sklearn.metrics import mean_squared_error, r2_score

In [40]:
mean_squared_error(y_test, y_pred)

2992.581229301017

In [41]:
r2_score(y_test, y_pred)

0.4384316213369279