Multiple Model Training , pipeline and column Transformer .

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
# Predict  
# what is the time ?  if anyone is visting the restaurant is it lunch or dinner ?
# time is the target variable and rest are the features

In [5]:
df["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [6]:
# EDA >> subjective 

# encoding , missing value treatment ,scaling >> automate

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [8]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [9]:
# no nullvalue still we will see  the null  value  imputation as well  
# since time is nominal variable , then we willuse label encoding for the target variable 


from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df["time"] = encoder.fit_transform(df["time"])
df

     total_bill   tip     sex smoker   day  time  size
0         16.99  1.01  Female     No   Sun     0     2
1         10.34  1.66    Male     No   Sun     0     3
2         21.01  3.50    Male     No   Sun     0     3
3         23.68  3.31    Male     No   Sun     0     2
4         24.59  3.61  Female     No   Sun     0     4
..          ...   ...     ...    ...   ...   ...   ...
239       29.03  5.92    Male     No   Sat     0     3
240       27.18  2.00  Female    Yes   Sat     0     2
241       22.67  2.00    Male    Yes   Sat     0     2
242       17.82  1.75    Male     No   Sat     0     2
243       18.78  3.00  Female     No  Thur     0     2

[244 rows x 7 columns]

In [10]:
df["time"].unique()

array([0, 1])

In [11]:
x = df.drop("time",axis=1)
y = df["time"]

x

     total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [12]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [13]:
from  sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [15]:
x_train.head()

     total_bill   tip   sex smoker   day  size
228       13.28  2.72  Male     No   Sat     2
208       24.27  2.03  Male    Yes   Sat     2
96        27.28  4.00  Male    Yes   Fri     2
167       31.71  4.50  Male     No   Sun     4
84        15.98  2.03  Male     No  Thur     2

In [16]:
x_test.head()

     total_bill   tip     sex smoker   day  size
24        19.82  3.18    Male     No   Sat     2
6          8.77  2.00    Male     No   Sun     2
153       24.55  2.00    Male     No   Sun     4
211       25.89  5.16    Male    Yes   Sat     4
198       13.00  2.00  Female    Yes  Thur     2

In [17]:
#  handling the missing value
# data encoding 
# featuture scaling

from sklearn.impute import SimpleImputer # for handling the missing value
from sklearn.preprocessing import OneHotEncoder # for encoding the categorical variable
from sklearn.preprocessing import StandardScaler # for feature scaling

from sklearn.pipeline  import Pipeline # for creating the pipeline >> a sequence of  data transformation steps and a final estimator
from sklearn.compose import ColumnTransformer # for applying different transformations to different columns of the data

In [18]:
df.sample(1)

    total_bill   tip   sex smoker  day  time  size
17       16.29  3.71  Male     No  Sun     0     3

In [19]:
cat_cols =["sex","smoker","day"]
num_cols = ["total_bill","tip","size"]

In [20]:
# feature engineering automation using  pipeline and column transformer 

num_pipeline =  Pipeline(steps=[("imputation",SimpleImputer(strategy="median")),
                ("scaling",StandardScaler())])

cat_pipeline =Pipeline(steps =  [("imputation",SimpleImputer(strategy="most_frequent")),
                                  ("encoding",OneHotEncoder(drop='first'))])

In [21]:
preprocessor  =  ColumnTransformer([("num_pipeline", num_pipeline, num_cols),
                   ("cat_pipeline", cat_pipeline, cat_cols)])

In [22]:
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['total_bill', 'tip', 'size']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder(drop='first'))]),
                                 ['sex', 'smoker', 'day'])])

In [23]:
X_train =  preprocessor.fit_transform(x_train)
X_train

array([[-0.79306155, -0.2580329 , -0.61214068, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.46322744, -0.74211442, -0.61214068, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.80730659,  0.6399734 , -0.61214068, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.65383098, -1.46472887, -0.61214068, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.64749986,  0.32426806, -0.61214068, ...,  0.        ,
         1.        ,  0.        ],
       [ 2.75289699, -0.41237773,  0.45363997, ...,  1.        ,
         0.        ,  0.        ]], shape=(195, 8))

In [24]:
X_test = preprocessor.transform(x_test)
X_test

array([[-0.04546101,  0.06468811, -0.61214068,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [-1.30860871, -0.76316144, -0.61214068,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [ 0.4952348 , -0.76316144,  1.51942062,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [ 0.64841289,  1.45379161,  1.51942062,  1.        ,  1.        ,
         1.        ,  0.        ,  0.        ],
       [-0.82506891, -0.76316144, -0.61214068,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ],
       [-0.26608319, -0.76316144, -0.61214068,  1.        ,  1.        ,
         0.        ,  1.        ,  0.        ],
       [ 0.93990852, -0.37028369, -0.61214068,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ],
       [-0.88451116, -0.39834638, -0.61214068,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [-0.62159354,  0.09976649, -0.61214068,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [-0.55300633, -0.06159402, -0.61214068,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ],
       [-0.22035838, -0.06159402, -0.61214068,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [-1.0799847 , -1.13499218, -0.61214068,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [-1.09370214, -1.11394516, -0.61214068,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [-0.65588714, -0.76316144, -0.61214068,  1.        ,  1.        ,
         0.        ,  1.        ,  0.        ],
       [-1.1600031 , -0.88242791, -1.67792133,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [-0.18034918, -1.21216459,  0.45363997,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [-0.17234734,  0.6399734 ,  0.45363997,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ],
       [ 0.15572813,  0.58384801, -0.61214068,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [-0.43069248, -0.43342476, -0.61214068,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [ 2.39738664,  1.34154082,  2.58520127,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [ 0.05399044, -0.4474561 ,  1.51942062,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [ 0.04941796,  0.18395458,  0.45363997,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [-0.67532018,  0.6399734 , -0.61214068,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ],
       [-1.21944535, -1.14902353, -0.61214068,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [ 0.07799596,  0.28918969,  0.45363997,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ],
       [-0.97481765, -0.54567554, -0.61214068,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [-1.1371407 , -0.966616  , -0.61214068,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [ 0.57868257,  1.34154082, -0.61214068,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ],
       [-0.42612   , -0.76316144,  1.51942062,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [ 3.19528447,  1.34154082,  3.65098192,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [ 2.04073317,  0.6399734 ,  0.45363997,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [-1.42635008, -1.1560392 , -0.61214068,  1.        ,  1.        ,
         1.        ,  0.        ,  0.        ],
       [-0.27522815, -0.52462852,  1.51942062,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [ 0.00826564,  0.08573514, -0.61214068,  1.        ,  1.        ,
         1.        ,  0.        ,  0.        ],
       [-0.37125023,  0.28918969,  0.45363997,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [ 0.44150815, -0.11771942,  1.51942062,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [-0.93595156, -1.11394516, -0.61214068,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ],
       [ 2.6168657 ,  1.34154082,  1.51942062,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ],
       [-0.80677899, -0.23698588, -0.61214068,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [ 0.28032822, -0.76316144, -0.61214068,  1.        ,  1.        ,
         1.        ,  0.        ,  0.        ],
       [-1.10970582, -1.28933701, -0.61214068,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [-0.65131466, -0.76316144, -0.61214068,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ],
       [ 0.42664759, -0.37729936, -0.61214068,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [-1.13028198, -0.99467869,  0.45363997,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [-1.12913886, -0.76316144, -0.61214068,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ],
       [-1.96018717, -1.46472887, -1.67792133,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ],
       [-1.10056086, -1.03677274, -0.61214068,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ],
       [-0.17463358, -0.54567554,  0.45363997,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [-1.44692625, -1.1560392 , -0.61214068,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ]])

In [25]:
# now data is ready  ,lets build the multiple models  

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [26]:
models  = {"Logistic Regression":LogisticRegression(),
           "Decision Tree":DecisionTreeClassifier(),
           "Support vector classifier":SVC(),
           "Random Forest":RandomForestClassifier()}
models

{'Logistic Regression': LogisticRegression(),
 'Decision Tree': DecisionTreeClassifier(),
 'Support vector classifier': SVC(),
 'Random Forest': RandomForestClassifier()}

In [27]:
for i in range(len(models)):
    print(list(models.values())[i])

LogisticRegression()
DecisionTreeClassifier()
SVC()
RandomForestClassifier()

In [28]:
from sklearn.metrics import accuracy_score

def  model_train_eval(X_train , X_test ,y_train, y_test, models):
    evaluation= {}
    for i in range(len(models)):
        model = list(models.values())[i]
        model.fit(X_train,y_train)
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test,y_pred)
        evaluation[list(models.keys())[i]] = acc
    return evaluation

In [29]:
model_train_eval(X_train , X_test ,y_train, y_test, models)

{'Logistic Regression': 1.0,
 'Decision Tree': 0.9387755102040817,
 'Support vector classifier': 0.9795918367346939,
 'Random Forest': 0.9591836734693877}

# Random Forest Classifier Implementation

In [30]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf

RandomForestClassifier()

In [31]:
# hyperparameter tuning >> grid search cv , random search cv , bayesian optimization

from sklearn.model_selection import RandomizedSearchCV
params = {'max_depth': [1,2,3,4,5,10, None],
          "n_estimators":[30,40,50,100,200,300,400,500],
          "criterion":['gini','entropy']}

In [32]:
clf=RandomizedSearchCV(estimator=rf, param_distributions=params, n_iter=10, cv=5, verbose=3, random_state=42, scoring = "accuracy")

In [33]:
clf

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 4, 5, 10, None],
                                        'n_estimators': [30, 40, 50, 100, 200,
                                                         300, 400, 500]},
                   random_state=42, scoring='accuracy', verbose=3)

In [34]:
clf.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=gini, max_depth=10, n_estimators=30;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, n_estimators=30;, score=0.923 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, n_estimators=30;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, n_estimators=30;, score=0.897 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, n_estimators=30;, score=0.949 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=2, n_estimators=40;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=2, n_estimators=40;, score=0.923 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=2, n_estimators=40;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=2, n_estimators=40;, score=0.923 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=2, n_estimators=40;, score=0.949 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=200;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=200;, score=0.872 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=200;, score=0.897 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=200;, score=0.897 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=200;, score=0.872 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, n_estimators=500;, score=0.974 total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, n_estimators=500;, score=0.923 total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, n_estimators=500;, score=0.974 total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, n_estimators=500;, score=0.949 total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, n_estimators=500;, score=0.949 total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, n_estimators=50;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, n_estimators=50;, score=0.923 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, n_estimators=50;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, n_estimators=50;, score=0.923 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, n_estimators=50;, score=0.923 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=2, n_estimators=300;, score=0.974 total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=2, n_estimators=300;, score=0.974 total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=2, n_estimators=300;, score=0.974 total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=2, n_estimators=300;, score=0.923 total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=2, n_estimators=300;, score=0.949 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=4, n_estimators=50;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=4, n_estimators=50;, score=0.974 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=4, n_estimators=50;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=4, n_estimators=50;, score=0.923 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=4, n_estimators=50;, score=0.949 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=2, n_estimators=100;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=2, n_estimators=100;, score=0.974 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=2, n_estimators=100;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=2, n_estimators=100;, score=0.923 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=2, n_estimators=100;, score=0.949 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.974 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.923 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=2, n_estimators=50;, score=0.949 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, n_estimators=200;, score=0.974 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, n_estimators=200;, score=0.923 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, n_estimators=200;, score=0.974 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, n_estimators=200;, score=0.949 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, n_estimators=200;, score=0.949 total time=   0.0s

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 4, 5, 10, None],
                                        'n_estimators': [30, 40, 50, 100, 200,
                                                         300, 400, 500]},
                   random_state=42, scoring='accuracy', verbose=3)

In [35]:
clf.best_params_

{'n_estimators': 300, 'max_depth': 2, 'criterion': 'entropy'}

In [36]:
clf.best_score_

np.float64(0.9589743589743589)

In [37]:
final_model = clf.best_estimator_
y_pred =final_model.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1])

In [38]:
# internal homework 

# use total_bill as target variable and make it a regressor problem
# automate fe , training testing and also random foresregressor with mlr and svr